# Generated by Django 3.2.9 on 2021-11-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=30)),
                ('metric_name', models.CharField(max_length=30)),
                ('metric_desc', models.CharField(blank=True, max_length=255)),
                ('metric_topic', models.CharField(blank=True, max_length=255)),
                ('business_type', models.IntegerField(blank=True, choices=[(1, 'Ssp')])),
                ('metric_filed', models.CharField(blank=True, max_length=30)),
                ('time_cycle', models.CharField(blank=True, max_length=30)),
                ('metric_dim', models.JSONField(blank=True, default=None)),
                ('metric_alias', models.CharField(blank=True, max_length=30)),
                ('metric_owner', models.IntegerField(blank=True, default=0)),
                ('metric_level', models.IntegerField(blank=True, default=0)),
                ('metric_power', models.JSONField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.IntegerField(default=0)),
            ],
        ),
    ]
