# Generated by Django 4.0.3 on 2022-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemListModel',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('create_by', models.CharField(max_length=150)),
                ('modify_by', models.CharField(max_length=150)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
