# Generated by Django 4.0.3 on 2022-04-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsModel', '0002_filesystemlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfoModel',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('create_by', models.CharField(max_length=150)),
                ('modify_by', models.CharField(max_length=150)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
