# Generated by Django 4.0.3 on 2022-04-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsModel', '0003_metainfomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metainfomodel',
            options={'verbose_name': '词根信息（元信息）'},
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='create_by',
            field=models.CharField(max_length=150, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='create_time',
            field=models.DateTimeField(auto_created=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增键'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='key',
            field=models.CharField(max_length=30, verbose_name='元数据英文KEY'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='modify_by',
            field=models.CharField(max_length=150, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='type',
            field=models.IntegerField(verbose_name='元数据类型.1:业务线;'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='value',
            field=models.CharField(max_length=30, verbose_name='元数据中文值'),
        ),
    ]
