# Generated by Django 4.0.3 on 2022-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsModel', '0005_alter_metainfomodel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metainfomodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='metainfomodel',
            name='key',
        ),
        migrations.AddField(
            model_name='metainfomodel',
            name='label',
            field=models.CharField(default=None, max_length=30, verbose_name='元数据中文值'),
        ),
        migrations.AlterField(
            model_name='metainfomodel',
            name='value',
            field=models.CharField(max_length=30, verbose_name='元数据英文KEY'),
        ),
    ]
