# Generated by Django 4.0.3 on 2022-04-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsModel', '0008_metainfomodel_parent_id_alter_metainfomodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metainfomodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Business'), (2, 'Metrics'), (3, 'Time Cycle'), (4, 'Dim'), (5, 'Dim Value')], verbose_name='元数据类型.1:业务线;2:指标词根'),
        ),
    ]
